<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<PublishReadyToRunComposite>true</PublishReadyToRunComposite>
		<EventSourceSupport>false</EventSourceSupport>
		<UseSystemResourceKeys>true</UseSystemResourceKeys>
		<InvariantGlobalization>true</InvariantGlobalization>
		<SelfContained>true</SelfContained>
		<RuntimeIdentifier>linux-x64</RuntimeIdentifier>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.AutoScaling" Version="4.0.3.5" />
    <PackageReference Include="AWSSDK.CloudWatch" Version="4.0.4.3" />
    <PackageReference Include="AWSSDK.CloudWatchLogs" Version="4.0.8.4" />
    <PackageReference Include="AWSSDK.Core" Version="4.0.0.32" />
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="4.0.7" />
    <PackageReference Include="AWSSDK.EC2" Version="4.0.40.4" />
    <PackageReference Include="AWSSDK.ElasticLoadBalancingV2" Version="4.0.2.6" />
    <PackageReference Include="AWSSDK.IdentityManagement" Version="4.0.3.7" />
    <PackageReference Include="AWSSDK.Lambda" Version="4.0.2.13" />
    <PackageReference Include="AWSSDK.SecretsManager" Version="4.0.1.6" />
    <PackageReference Include="AWSSDK.SecurityToken" Version="4.0.2.6" />
    <PackageReference Include="AWSSDK.SimpleNotificationService" Version="4.0.1.6" />
    <PackageReference Include="AWSSDK.SQS" Version="4.0.1.8" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="NUnit" Version="4.4.0" />
    <PackageReference Include="NUnit.Analyzers" Version="4.10.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="NUnit3TestAdapter" Version="5.2.0" />
    <PackageReference Include="NUnitLite" Version="4.4.0" />
  </ItemGroup>

</Project>
