<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <AWSProjectType>Lambda</AWSProjectType>
    <!-- This property makes the build directory similar to a publish directory and helps the AWS .NET Lambda Mock Test Tool find project dependencies. -->
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <!-- Generate ready to run images during publishing to improve cold start time. -->
    <PublishReadyToRun>true</PublishReadyToRun>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Amazon.Lambda.APIGatewayEvents" Version="2.7.3" />
    <PackageReference Include="Amazon.Lambda.AspNetCoreServer.Hosting" Version="1.10.0" />
    <PackageReference Include="Amazon.Lambda.CloudWatchEvents" Version="4.4.1" />
    <PackageReference Include="Amazon.Lambda.Core" Version="2.8.1" />
    <PackageReference Include="Amazon.Lambda.RuntimeSupport" Version="1.14.3" />
    <PackageReference Include="Amazon.Lambda.Serialization.SystemTextJson" Version="2.4.5" />
    <PackageReference Include="AWSSDK.APIGateway" Version="4.0.6.10" />
    <PackageReference Include="AWSSDK.BedrockRuntime" Version="4.0.17.5" />
    <PackageReference Include="AWSSDK.Core" Version="4.0.5" />
    <PackageReference Include="AWSSDK.DynamoDBv2" Version="4.0.17.11" />
    <PackageReference Include="AWSSDK.S3" Version="4.0.22.1" />
    <PackageReference Include="AWSSDK.StepFunctions" Version="4.0.2.22" />
    <PackageReference Include="AWSXRayRecorder.Core" Version="2.16.0" />
    <PackageReference Include="AWSXRayRecorder.Handlers.AwsSdk" Version="2.14.0" />
    <PackageReference Include="Microsoft.AspNetCore.StaticFiles" Version="2.3.9" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.7" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="NUnit" Version="4.5.1" />
    <PackageReference Include="NUnitLite" Version="4.5.1" />
  </ItemGroup>


  <ItemGroup>
    <ProjectReference Include="..\ProjectTestsLib\ProjectTestsLib.csproj" />
  </ItemGroup>

</Project>
